"""Tests for Python port of Java classes from the coords hierarchy.

Modules
-------
test_abstractcoordconverter.py
test_abstractcoordconverterij.py
test_abstractvectorfieldvalue.py
test_cartesianvectorfieldvalue.py
test_coordconverter.py
test_coordconverterij.py
test_coordconverters.py
test_cylindricalcoordconverter.py
test_cylindricaltocartesianbasistransformation.py
test_cylindricaltocartesianjacobian.py
test_cylindricalvectorfieldvalue.py
test_latitudinalcoordconverter.py
test_latitudinaltocartesianjacobian.py
test_latitudinalvector.py
test_pointonaxisexception.py
test_polarcoordconverter.py
test_polartocartesianjacobian.py
test_polarvector.py
test_radeccoordconverter.py
test_radecvector.py
test_sphericalcoordconverter.py
test_sphericaltocartesianbasistransformation.py
test_sphericaltocartesianjacobian.py
test_sphericalvectorfieldvalue.py
test_transformation.py
test_transformationij.py
test_vectorfieldvalue.py
test_vectorfieldvalueconversions.py

Packages
--------
"""
