"""Tests for Python port of Java classes from the crucible.core.math.coords hierarchy.

Modules
-------
test_abstractcoordconverter.py
test_abstractcoordconverterij.py
test_abstractvectorfieldvalue.py
test_cartesianvectorfieldvalue.py
test_coordconverter.py
test_coordconverterij.py
test_coordconverters.py
test_cylindricalcoordconverter.py
test_cylindricaltocartesianbasistransformation.py
test_cylindricaltocartesianjacobian.py
test_cylindricalvectorfieldvalue.py
test_latitudinalcoordconverter.py
test_latitudinaltocartesianjacobian.py
test_latitudinalvector.py
test_pointonaxisexception.py
test_polarcoordconverter.py
test_PolarToCartesianJacobian.py
test_polarvector.py
test_RaDecCoordConverter.py
test_RaDecVector.py
test_SphericalCoordConverter.py
test_SphericalToCartesianBasisTransformation.py
test_SphericalToCartesianJacobian.py
test_SphericalVector.py
test_SphericalVectorFieldValue.py
test_transformation.py
test_TransformationIJ.py
test_vectorfieldvalue.py
test_VectorFieldValueConversions.py

Packages
--------
"""
