"""Run-time exception for Crucible code.

Parent of all runtime exceptions generated by the Crucible library.

Authors
-------
F.S. Turner
Eric Winter (eric.winter@jhuapl.edu)
"""


from emmpy.crucible.core.exceptions.crucibleexception import CrucibleException


class CrucibleRuntimeException(CrucibleException):
    """Run-time exception for Crucible code."""
