"""Run-time exception for Crucible code.

Parent of all runtime exceptions generated by the Crucible library.

author F.S.Turner
"""


from emmpy.crucible.core.exceptions.CrucibleException import CrucibleException


class CrucibleRuntimeException(CrucibleException):
    """Run-time exception for Crucible code."""
