"""Base exception class for crucible code.

Parent of all exceptions generated by the crucible library.

@author F.S.Turner
"""


class CrucibleException(Exception):
    """Base exception class for crucible code."""
