"""Base exception class for Crucible code.

Parent of all exceptions generated by the crucible library.

Authors
-------
F.S.Turner
Eric Winter (eric.winter@jhuapl.edu)
"""


class CrucibleException(Exception):
    """Base exception class for Crucible code."""
