# package crucible.core.exceptions;

# /**
#  * Parent of all exceptions generated by the crucible library.
#  * 
#  * @author F.S.Turner
#  */

class CrucibleException(Exception):

    #   /**
    #    * Default serial version UID.
    #    */
    serialVersionUID = 1

    def __init__(self, *args):
        Exception.__init__(self, *args)

    #   public CrucibleException(String message) {
    #     super(message);
    #   }

    #   public CrucibleException(Throwable cause) {
    #     super(cause);
    #   }

    #   public CrucibleException(String message, Throwable cause) {
    #     super(message, cause);
    #   }

    # }
