"""Parent of all runtime exceptions generated by the crucible library.

@author F.S.Turner
"""


from emmpy.crucible.core.exceptions.crucibleexception import CrucibleException


class CrucibleRuntimeException(CrucibleException):

    # Default serial version UID.
    serialVersionUID = 1
